[workspace]
resolver = "2"
members = ["wgpu-in-app", "app-surface", "cargo-so"]
default-members = ["wgpu-in-app"]

[workspace.dependencies]
bytemuck = { version = "1.13", features = ["derive"] }
glam = "0.24"
log = "0.4"
noise = { version = "0.8", default-features = false }
pollster = "0.3"
rand = "0.7.2"
wgpu = "0.16.2"
# wgpu = { git = "https://github.com/gfx-rs/wgpu", rev = "757245cd" }
# wgpu = { path = "../../forks/wgpu/wgpu" }
# wgpu = { git = "https://github.com/jinleili/wgpu", branch="visionOS" }

async-executor = "1.0"
winit = "0.27.5"
raw-window-handle = "0.5"
env_logger = "0.10"

# macOS, iOS
libc = "0.2.147"
objc = "0.2.7"
core-graphics = "0.23.1"

# android target
android_logger = "0.13"
jni = "0.21"
jni_fn = "0.1"
ndk-sys = "0.4.1"
ash = "0.37.3"

# wasm target
web-sys = "0.3.64"
wasm-bindgen = "0.2.87"
js-sys = "0.3.64"
wasm-bindgen-futures = "0.4.34"
# parking_lot 0.12 switches from `winapi` to `windows`; permit either
parking_lot = ">=0.11,<0.13"
