[package]
name = "app-surface"
authors = ["jinleili"]
description = "Integrate wgpu into your existing iOS and Android apps."
edition = "2021"
version = "0.3.1"
rust-version = "1.64"
repository = "https://github.com/jinleili/wgpu-in-app"
keywords = ["android", "ios", "app", "wgpu"]
license = "MIT"

[lib]
crate-type = ["rlib"]

[features]
default = []
webgl = ["wgpu/webgl"]

[dependencies]
log.workspace = true
glam.workspace = true
pollster.workspace = true
wgpu.workspace = true

wgpu-hal = "0.16.2"
metal = "0.24.0"
wgpu-types = "0.16.1"
foreign-types = "0.3.2"

[target.'cfg(any(not(target_os = "ios"), not(target_os = "android")))'.dependencies]
async-executor.workspace = true
winit.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc.workspace = true
objc.workspace = true
raw-window-handle.workspace = true

[target.'cfg(target_os = "ios")'.dependencies]
core-graphics.workspace = true
env_logger.workspace = true
libc.workspace = true
objc.workspace = true

[target.'cfg(target_os = "android")'.dependencies]
android_logger.workspace = true
jni.workspace = true
ndk-sys.workspace = true
raw-window-handle.workspace = true
# hal = { workspace = true, features = ["renderdoc", "vulkan"] }
ash.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { workspace = true, features = [
    "Document",
    "Window",
    "Location"
] }
wasm-bindgen.workspace = true
